import { Component, HostListener } from '@angular/core';

@Component({selector:'app-root',standalone:true,template:`
<nav class="nav"><div class="nav-inner"><a class="brand" href="#home">RH<span>.</span></a><button class="menu" (click)="open=!open" aria-label="Toggle navigation">☰</button><div class="nav-links" [class.open]="open"><a href="#about" (click)="open=false">About</a><a href="#experience" (click)="open=false">Experience</a><a href="#skills" (click)="open=false">Skills</a><a href="#work" (click)="open=false">Work</a><a href="#contact" (click)="open=false">Contact</a></div></div></nav>
<main>
<section id="home" class="hero"><div class="glow one"></div><div class="glow two"></div><div class="container hero-content"><div class="eyebrow">SOFTWARE DEVELOPER · CHENNAI</div><h1>Building software that <em>solves real problems.</em></h1><p>I’m Riyas Hameed. I specialize in C#, ASP.NET Core, .NET MAUI and AI-driven applications—building scalable systems, polished experiences and reliable software.</p><div class="buttons"><a class="btn primary" href="#work">Explore my work <span>↗</span></a><a class="btn" href="#contact">Get in touch</a></div><div class="scroll">SCROLL TO EXPLORE <span>↓</span></div></div></section>
<section id="about" class="section"><div class="container split"><div><div class="eyebrow">01 — ABOUT</div><h2>Engineering with curiosity.</h2></div><div class="copy"><p>My experience spans cross-platform UI engineering, backend APIs and modern AI workflows. At Syncfusion, I’ve worked across .NET MAUI controls, ASP.NET Core services, PostgreSQL and AI-powered products.</p><p>I enjoy taking complex technical problems, understanding them deeply, and turning them into maintainable, scalable solutions.</p></div></div></section>
<section id="experience" class="section dark"><div class="container"><div class="eyebrow">02 — EXPERIENCE</div><h2>Where I’ve built.</h2><article class="experience"><div class="exp-head"><div><h3>Syncfusion Software Pvt. Ltd.</h3><p>Software Developer</p></div><span>2021 — PRESENT · CHENNAI</span></div><div class="exp-grid"><div><b>01</b><p>Developed and maintained cross-platform .NET MAUI UI components and reusable custom controls.</p></div><div><b>02</b><p>Led feature development and bug resolution across 10+ UI controls, diagnosing memory leaks and performance issues.</p></div><div><b>03</b><p>Developed RESTful APIs using ASP.NET Core, EF Core and PostgreSQL with scalability in mind.</p></div><div><b>04</b><p>Contributed to AI Agent and RAG workflows involving prompt engineering, web search, URL context and vector retrieval.</p></div><div><b>05</b><p>Integrated image generation models and developed Azure Functions for asynchronous background processing.</p></div><div><b>06</b><p>Built TypeScript AI workflow features and LLM token usage tracking and analytics.</p></div></div></article></div></section>
<section id="skills" class="section"><div class="container"><div class="eyebrow">03 — SKILLS</div><h2>My toolkit.</h2><div class="skill-grid">@for (s of skills; track s.name) {<button class="skill-card" [class.active]="activeSkill===s.name" (click)="activeSkill=s.name"><span class="icon">{{s.icon}}</span><strong>{{s.name}}</strong><small>{{s.items}}</small><span class="plus">{{activeSkill===s.name?'×':'+'}}</span></button>}</div><div class="skill-detail" *ngIf="activeSkill"><span>Focused area</span><strong>{{activeSkill}}</strong><p>{{skillDetails[activeSkill]}}</p></div></div></section>
<section id="work" class="section dark"><div class="container"><div class="eyebrow">04 — SELECTED WORK</div><h2>Things I’ve worked on.</h2><div class="work-grid">@for (p of projects; track p.title) {<article class="work-card" (click)="selected=selected===p.title?'':p.title"><div class="work-top"><span>{{p.number}}</span><span>↗</span></div><h3>{{p.title}}</h3><p>{{p.text}}</p><div class="tags">@for(t of p.tags; track t){<span>{{t}}</span>}</div><div class="expand" [class.show]="selected===p.title">Click to explore the technical focus →</div></article>}</div></div></section>
<section id="contact" class="section contact"><div class="container"><div class="eyebrow">05 — CONTACT</div><h2>Let’s build something useful.</h2><p>Open to conversations about software engineering, backend development and AI-powered applications.</p><div class="contact-links"><a href="mailto:riyashameed50@gmail.com">✉ Email <span>riyashameed50@gmail.com</span></a><a href="tel:8778947529">☎ Phone <span>8778947529</span></a><a href="https://linkedin.com/in/riyas-hameed-51b254217" target="_blank">in LinkedIn <span>View profile ↗</span></a></div></div></section>
</main><footer><div class="container">© 2026 Riyas Hameed <span>Software Developer</span></div></footer>`,styles:[]})
export class AppComponent { open=false; activeSkill=''; selected=''; skills=[{name:'Languages',icon:'⌘',items:'C# · TypeScript · SQL · LINQ'},{name:'Backend',icon:'◈',items:'ASP.NET Core · REST · EF Core'},{name:'Database',icon:'◫',items:'PostgreSQL'},{name:'Cloud',icon:'☁',items:'Azure Functions'},{name:'AI & LLM',icon:'✦',items:'Prompt Engineering · RAG · Vector Search'},{name:'Spoken',icon:'◉',items:'English · Tamil'}]; skillDetails:any={'Languages':'Strong C# foundation with hands-on TypeScript and SQL development.','Backend':'API design and implementation using ASP.NET Core and Entity Framework Core.','Database':'PostgreSQL experience focused on reliable and maintainable data access.','Cloud':'Azure Functions for background jobs, asynchronous processing and database operations.','AI & LLM':'Practical experience with LLM workflows, RAG, vector retrieval and prompt engineering.','Spoken':'Professional communication in English and Tamil.'}; projects=[{number:'01',title:'AI Agent Platform',text:'LLM-based workflows and prompt engineering for an AI-driven agent platform.',tags:['LLMs','Prompt Engineering','TypeScript']},{number:'02',title:'RAG & Knowledge Retrieval',text:'Web search, URL context and vector knowledge-base retrieval for LLM applications.',tags:['RAG','Vector Search','Knowledge Base']},{number:'03',title:'Image Generation',text:'Image generation model integration with Azure Functions for asynchronous processing.',tags:['Azure','AI','Async']},{number:'04',title:'LLM Usage Analytics',text:'Token usage tracking and analytics for monitoring AI response consumption.',tags:['TypeScript','Tokens','Analytics']}];}